### PR TITLE
add dataset paths to dataloader

### PR DESCRIPTION
**Pull request by arya1106**

### CODE REVIEW

**Comment by jinensetpal** [comment]
The dataset isn't uploaded, maybe you didn't run `dvc push -r origin`?
2022-10-22-134824_690x196_scrot

**Review by jinensetpal — CHANGES_REQUESTED** [review]
Data push required (see above)

**Comment by arya1106** [comment]
Seems like everything's up to date on my end. Let's tackle this at the team sync?
image

**Comment by jinensetpal** [comment]
Sounds good!

**Review by jinensetpal — APPROVED** [review]
I ran `dvc pull -r origin`, and it worked now. Merging!

**Pull request merged**
